2019-07-10 16:07:06,587 INFO: Microblog startup [in /Users/EZ/Documents/git_projects/microblog/app/__init__.py:40]
2019-07-10 16:07:30,134 INFO: Microblog startup [in /Users/EZ/Documents/git_projects/microblog/app/__init__.py:40]
2019-07-10 17:05:20,403 INFO: Microblog startup [in /Users/EZ/Documents/git_projects/microblog/app/__init__.py:40]
2019-07-10 17:06:57,278 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTYyNzkzMzg2LjU0MzM0Mn0.NdJkerzgrNurClySQwxoVoO_WrCXdvvaN3jQSk113aQ [GET] [in /Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/EZ/Documents/git_projects/microblog/app/routes.py", line 118, in reset_password
    form = ResetPasswordForm()
NameError: name 'ResetPasswordForm' is not defined
2019-07-10 17:07:38,139 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTYyNzkzMzg2LjU0MzM0Mn0.NdJkerzgrNurClySQwxoVoO_WrCXdvvaN3jQSk113aQ [GET] [in /Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/EZ/Documents/git_projects/microblog/app/routes.py", line 118, in reset_password
    form = ResetPasswordForm()
NameError: name 'ResetPasswordForm' is not defined
2019-07-10 17:07:57,891 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTYyNzkzMzg2LjU0MzM0Mn0.NdJkerzgrNurClySQwxoVoO_WrCXdvvaN3jQSk113aQ [GET] [in /Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/EZ/Documents/git_projects/microblog/app/routes.py", line 118, in reset_password
    form = ResetPasswordForm()
NameError: name 'ResetPasswordForm' is not defined
2019-07-10 17:08:35,355 INFO: Microblog startup [in /Users/EZ/Documents/git_projects/microblog/app/__init__.py:40]
2019-07-15 13:46:01,132 INFO: Microblog startup [in /Users/EZ/Documents/git_projects/microblog/app/__init__.py:42]
2019-07-15 13:46:07,597 ERROR: Exception on /login [GET] [in /Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/EZ/Documents/git_projects/microblog/app/routes.py", line 46, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/EZ/Documents/git_projects/microblog/app/templates/base.html", line 3, in template
    {% block title %}
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/EZ/Documents/git_projects/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/EZ/Documents/git_projects/microblog/app/templates/base.html", line 3, in template
    {% block title %}
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 888, in subparse
    self.stream.expect('block_end')
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '{'
2019-07-15 13:52:38,338 INFO: Microblog startup [in /Users/EZ/Documents/git_projects/microblog/app/__init__.py:42]
